# Environment to debug stonne with gdbserver

FROM franciscomunoz/stonne_omega_img
LABEL maintainer=hansikam94@gmail.com
RUN apt-get update && apt-get install  -y git
RUN apt-get update && apt-get install gdbserver
WORKDIR /home
